# Generated by Django 5.2.9 on 2026-03-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Короткое название')),
                ('image', models.ImageField(upload_to='places/', verbose_name='Изображение')),
                ('city', models.CharField(default='Ташкент', max_length=100, verbose_name='Город')),
                ('country', models.CharField(default='Узбекистан', max_length=100, verbose_name='Страна')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный баннер')),
                ('force_closed', models.BooleanField(default=False, verbose_name='Временно закрыто')),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='Формат: {"1": ["09:00", "22:00"], "5": ["09:00", "23:00"]}', verbose_name='Расписание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
