# Generated by Django 5.2.9 on 2026-03-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iccu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Короткое название"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="Изображение"),
                ),
                (
                    "city",
                    models.CharField(
                        default="Ташкент", max_length=100, verbose_name="Город"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Узбекистан", max_length=100, verbose_name="Страна"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активный баннер"),
                ),
                (
                    "force_closed",
                    models.BooleanField(default=False, verbose_name="Временно закрыто"),
                ),
                (
                    "schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Формат: {"1": ["09:00", "22:00"], "5": ["09:00", "23:00"]}',
                        verbose_name="Расписание",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
            },
        ),
        migrations.CreateModel(
            name="TicketSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("link", "Ссылка"), ("info", "Информация")],
                        default="link",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "link_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Текст ссылки"
                    ),
                ),
                ("link_url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "icon",
                    models.ImageField(
                        blank=True, upload_to="ticket_sources/", verbose_name="Иконка"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Источник билетов",
                "verbose_name_plural": "Источники билетов",
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="Place",
        ),
    ]
