# Generated by Django 5.2.9 on 2026-03-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iccu", "0002_banner_ticketsource_delete_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="schedule",
            field=models.JSONField(blank=True, default=dict, verbose_name="Расписание"),
        ),
    ]
