# Generated by Django 5.2.9 on 2026-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iccu", "0003_alter_banner_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="city_en",
            field=models.CharField(
                default="Ташкент", max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="city_ru",
            field=models.CharField(
                default="Ташкент", max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="city_uz",
            field=models.CharField(
                default="Ташкент", max_length=100, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="country_en",
            field=models.CharField(
                default="Узбекистан", max_length=100, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="country_ru",
            field=models.CharField(
                default="Узбекистан", max_length=100, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="country_uz",
            field=models.CharField(
                default="Узбекистан", max_length=100, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="banner",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="banner",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="ticketsource",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="ticketsource",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="ticketsource",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="ticketsource",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="ticketsource",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="ticketsource",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
    ]
