# Generated by Django 5.2.9 on 2026-03-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iccu", "0004_banner_city_en_banner_city_ru_banner_city_uz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketsource",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="ticketsource",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="ticketsource",
            name="title_uz",
        ),
    ]
