# Generated by Django 5.2.9 on 2026-03-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iccu", "0005_remove_ticketsource_title_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Понедельник"),
                            (2, "Вторник"),
                            (3, "Среда"),
                            (4, "Четверг"),
                            (5, "Пятница"),
                            (6, "Суббота"),
                            (7, "Воскресенье"),
                        ],
                        unique=True,
                        verbose_name="День недели",
                    ),
                ),
                (
                    "is_working",
                    models.BooleanField(default=True, verbose_name="Рабочий день"),
                ),
                (
                    "force_closed",
                    models.BooleanField(default=False, verbose_name="Временно закрыто"),
                ),
                (
                    "open_time",
                    models.TimeField(blank=True, null=True, verbose_name="Открытие"),
                ),
                (
                    "close_time",
                    models.TimeField(blank=True, null=True, verbose_name="Закрытие"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заметка"
                    ),
                ),
                (
                    "note_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заметка"
                    ),
                ),
                (
                    "note_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заметка"
                    ),
                ),
                (
                    "note_uz",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заметка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписание",
                "ordering": ["weekday"],
            },
        ),
        migrations.RemoveField(
            model_name="banner",
            name="force_closed",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="schedule",
        ),
    ]
