# Generated by Django 5.2.9 on 2026-03-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccu', '0007_iticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=500, null=True, verbose_name='Вопрос')),
                ('question_en', models.CharField(max_length=500, null=True, verbose_name='Вопрос')),
                ('question_uz', models.CharField(max_length=500, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_uz', models.TextField(null=True, verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы (ЧЗВ)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('prohibited', 'Запрещается'), ('recommended', 'Рекомендуется'), ('dress_code', 'Дресс-код')], max_length=20, verbose_name='Категория')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='Текст')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='Текст')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='Текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила и рекомендации',
                'ordering': ['category', 'order'],
            },
        ),
    ]
