# Generated by Django 5.2.9 on 2026-03-17 05:59

import django.db.models.deletion
from django.db import migrations, models


CATEGORY_MAP = {
    "prohibited": "Запрещается",
    "recommended": "Рекомендуется",
    "dress_code": "Дресс-код",
}


def migrate_categories_forward(apps, schema_editor):
    RuleCategory = apps.get_model("iccu", "RuleCategory")
    Rule = apps.get_model("iccu", "Rule")

    for order, (key, name) in enumerate(CATEGORY_MAP.items()):
        cat = RuleCategory.objects.create(name=name, name_ru=name, order=order)
        Rule.objects.filter(category_old=key).update(category=cat.id)


def migrate_categories_backward(apps, schema_editor):
    RuleCategory = apps.get_model("iccu", "RuleCategory")
    Rule = apps.get_model("iccu", "Rule")

    reverse_map = {v: k for k, v in CATEGORY_MAP.items()}
    for cat in RuleCategory.objects.all():
        old_value = reverse_map.get(cat.name, "prohibited")
        Rule.objects.filter(category=cat.id).update(category_old=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ("iccu", "0008_faq_rule"),
    ]

    operations = [
        # 1. Create RuleCategory model
        migrations.CreateModel(
            name="RuleCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("name_ru", models.CharField(max_length=100, null=True, verbose_name="Название")),
                ("name_en", models.CharField(max_length=100, null=True, verbose_name="Название")),
                ("name_uz", models.CharField(max_length=100, null=True, verbose_name="Название")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("icon", models.ImageField(upload_to="rule_category/", verbose_name="Икона")),
            ],
            options={
                "verbose_name": "Категория правил",
                "verbose_name_plural": "Категории правил",
                "ordering": ["order"],
            },
        ),
        # 2. Rename old category field
        migrations.RenameField(
            model_name="rule",
            old_name="category",
            new_name="category_old",
        ),
        # 3. Add new FK field (nullable temporarily)
        migrations.AddField(
            model_name="rule",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="iccu.rulecategory",
                verbose_name="Категория",
            ),
        ),
        # 4. Migrate data
        migrations.RunPython(migrate_categories_forward, migrate_categories_backward),
        # 5. Remove old field
        migrations.RemoveField(
            model_name="rule",
            name="category_old",
        ),
        # 6. Make FK non-nullable
        migrations.AlterField(
            model_name="rule",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="iccu.rulecategory",
                verbose_name="Категория",
            ),
        ),
        # 7. Update model options
        migrations.AlterModelOptions(
            name="rule",
            options={
                "ordering": ["category__order", "order"],
                "verbose_name": "Правило",
                "verbose_name_plural": "Правила и рекомендации",
            },
        ),
    ]
