# Generated by Django 5.2.9 on 2026-03-17 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iccu', '0009_rulecategory_alter_rule_options_alter_rule_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Комплекс')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Комплекс')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Комплекс')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Комплекс')),
                ('orienteer', models.CharField(blank=True, max_length=255, verbose_name='Ориентир')),
                ('orienteer_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ориентир')),
                ('orienteer_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ориентир')),
                ('orienteer_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ориентир')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Комплекс',
                'verbose_name_plural': 'Комплексы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Место')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Место')),
                ('full_name', models.CharField(blank=True, max_length=500, verbose_name='Расширенное название')),
                ('full_name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Расширенное название')),
                ('full_name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Расширенное название')),
                ('full_name_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Расширенное название')),
                ('icon', models.ImageField(blank=True, upload_to='places/', verbose_name='Иконка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на местоположение')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='iccu.complex', verbose_name='Комплекс')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['order'],
            },
        ),
    ]
